---

- name: Install Java 8 using apt.
  apt:
    name: "{{java.VERSION}}"
    state: present
  become: true

- name: Correct the alternatives to change default Java version.
  alternatives:
    name: java
    link: /bin/java
    path: "{{java.ALTERNATIVES}}"

- name: To download the maven3.6.3 package
  get_url:
    url: "{{maven.repo_URL}}"
    dest: /tmp

- name: Extract the maven3.6.3 package
  unarchive:
    src: /tmp/apache-maven-3.6.3-bin.tar.gz
    dest: /opt
    remote_src: yes
  become: true

- name: Updating the path for maven use
  file:
     state: link
     force: yes
     src: "{{maven.maven_binaries}}"
     dest: /usr/bin/mvn
  become: true

